using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TestAnim : MonoBehaviour
{
    Animator anim;

    // Start is called before the first frame update
    void Start()
    {
        anim = GetComponent<Animator>();    
    }

    // Update is called once per frame
    void Update()
    {
        /*if(Input.GetKeyDown(KeyCode.U))
        {
            anim.SetTrigger("TestTrigger");
        }
        if (Input.GetKeyDown(KeyCode.I))
        {
            anim.SetTrigger("TestTrigger2");
        }*/
    }

    public void Test()
    {
        Debug.Log("응 넌 바보됐어. 시간만 버렸어 ㅋㅋ");
    }
}
